name: backendTesting
on: ["push"]
jobs:
  unit-tests:
    runs-on: ubuntu:latest
    steps:
      - name: Setup Node
        uses: ./
        with:
          node-version: 20.11.1
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: test CI
        run: npm run tests:unit
        shell: bash