name: backendTesting
on: ["push"]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/Freddyede/test3.git
      - run: cd test3/api
      - run: sudo apt update && sudo apt upgrade && sudo apt i npm -y
      - run: npm install
      - run: npm run tests:unit