name: backendTesting
on: ["push"]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../../api
    name: init project
    steps:
      - run: npm install
      - run: npm run tests:unit