name: Node.js CI

on:
  push:
    branches: [ develop ] # Trigger the workflow on every commit to the develop branch.
  pull_request:
    branches: [ main ] # Trigger the workflow on pull requests targeting the main branch.

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'api'
    strategy:
      matrix:
        node-version: [20.11.1] # Define a matrix of Node.js versions to test.There would be 3 jobs for 12.x, 14.x, 16.x

    steps:
    - name: Initialized nodeJs 20.11.1
      uses: actions/setup-node@v2

    - name: Mise en cache des dépendances
      uses: actions/cache@v3
      with:
        node-version: 20.11.1
        cache: 'npm' # Step 2: Use npm caching for faster dependency installs.
        cache-dependency-path: './api/package-lock.json'

    - name: installation des dépendances npm
      run: npm install

    - name: unit test runner
      run: npm run tests:unit # Step 4: Run tests using the specified Node.js version.