name: backendTesting
on: ["push"]
jobs:
  unit-tests:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean global cache
        run: npm cache clean --force
      - name: Setup Node
        uses: ./
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: test CI
        run: npm run tests:unit
        shell: bash